export const API = {
  en: {
    "api.process.title": "Our API integration process",
    "api.process.subtitle": "A clear path from first contact to industrialization.",
    "api.process.step_chip": "Step",
    "api.process.step1.title": "Contact",
    "api.process.step1.desc": "Tell us about your context, systems, and objectives.",
    "api.process.step2.title": "Requirements",
    "api.process.step2.desc": "Scoping workshop: data, flows, security, SLAs, compliance.",
    "api.process.step3.title": "Integration",
    "api.process.step3.desc": "Connect to your API/ERP/TMS, staging environment, UAT validation.",
    "api.process.step4.title": "Industrialization",
    "api.process.step4.desc": "Production rollout, monitoring, continuous optimization and support.",

    "api.cta.title": "Ready to build with our API?",
    "api.cta.desc": "Partner with Fincargo to integrate finance workflows seamlessly.",
    "api.cta.button": "Contact partnership",

    "api.form.title": "API Integration – Partner Contact",
    "api.form.subtitle": "Get in touch to become an integration partner. We’ll respond shortly.",
  },
  fr: {
    "api.process.title": "Notre processus d’intégration API",
    "api.process.subtitle": "Un parcours clair, de la prise de contact à l’industrialisation.",
    "api.process.step_chip": "Étape",
    "api.process.step1.title": "Prise de contact",
    "api.process.step1.desc": "Expliquez‑nous votre contexte, vos systèmes et vos objectifs.",
    "api.process.step2.title": "Compréhension des besoins",
    "api.process.step2.desc": "Atelier de cadrage : données, flux, sécurité, SLA, conformité.",
    "api.process.step3.title": "Intégration",
    "api.process.step3.desc": "Connexion à vos API/ERP/TMS, environnement de test, validation UAT.",
    "api.process.step4.title": "Industrialisation",
    "api.process.step4.desc": "Mise en production, monitoring, optimisation continue et support.",

    "api.cta.title": "Prêt à construire avec notre API ?",
    "api.cta.desc": "Partenariat avec Fincargo pour des intégrations financières fluides.",
    "api.cta.button": "Contacter le partenariat",

    "api.form.title": "Intégration API – Contact Partenaires",
    "api.form.subtitle": "Contactez‑nous pour devenir partenaire d’intégration. Réponse rapide.",
  },
  es: {
    "api.process.title": "Nuestro proceso de integración de API",
    "api.process.subtitle": "Un recorrido claro, desde el primer contacto hasta la industrialización.",
    "api.process.step_chip": "Etapa",
    "api.process.step1.title": "Primer contacto",
    "api.process.step1.desc": "Cuéntenos su contexto, sistemas y objetivos.",
    "api.process.step2.title": "Comprensión de necesidades",
    "api.process.step2.desc": "Taller de alcance: datos, flujos, seguridad, SLA, cumplimiento.",
    "api.process.step3.title": "Integración",
    "api.process.step3.desc": "Conexión con su API/ERP/TMS, entorno de pruebas, validación UAT.",
    "api.process.step4.title": "Industrialización",
    "api.process.step4.desc": "Puesta en producción, monitoreo, optimización continua y soporte.",

    "api.cta.title": "¿Listo para construir con nuestra API?",
    "api.cta.desc": "Asóciese con Fincargo para integrar flujos financieros sin fricción.",
    "api.cta.button": "Contactar asociación",

    "api.form.title": "Integración de API – Contacto de socios",
    "api.form.subtitle": "Póngase en contacto para convertirse en socio de integración. Respuesta rápida.",
  },
  de: {
    "api.process.title": "Unser API‑Integrationsprozess",
    "api.process.subtitle": "Ein klarer Weg vom Erstkontakt bis zur Industrialisierung.",
    "api.process.step_chip": "Schritt",
    "api.process.step1.title": "Kontaktaufnahme",
    "api.process.step1.desc": "Beschreiben Sie Ihren Kontext, Ihre Systeme und Ziele.",
    "api.process.step2.title": "Bedarfsanalyse",
    "api.process.step2.desc": "Scoping‑Workshop: Daten, Flüsse, Sicherheit, SLAs, Compliance.",
    "api.process.step3.title": "Integration",
    "api.process.step3.desc": "Anbindung an Ihre API/ERP/TMS, Testumgebung, UAT‑Freigabe.",
    "api.process.step4.title": "Industrialisierung",
    "api.process.step4.desc": "Produktivsetzung, Monitoring, kontinuierliche Optimierung und Support.",

    "api.cta.title": "Bereit, mit unserer API zu bauen?",
    "api.cta.desc": "Partnerschaft mit Fincargo für nahtlose Finanz‑Workflows.",
    "api.cta.button": "Partnerschaft kontaktieren",

    "api.form.title": "API‑Integration – Partnerkontakt",
    "api.form.subtitle": "Kontaktieren Sie uns, um Integrationspartner zu werden. Schnelle Rückmeldung.",
  },
} as const;
