export const GENERAL = {
  en: {
    pricing: "Pricing",
    demo: "Demo",
    register: "Sign Up",
    login: "Log In",
    for_carriers: "For carriers",
    services: "Services",
    benefits: "Benefits",
    features: "Features",
    invite_your_freight_forwarder: "Invite your forwarders",
    invite_your_carriers: "Invite your carriers",
    faq: "FAQ",
    for_freight_forwarders: "For freight forwarders",
    invite_your_subcontractors: "Invite your register",
    company: "Company",
    about_us: "About us",
    contact: "Contact",
    Confidentiality: "Confidentiality & Security",
    legal_notice: "Legal Notice",
    cookies: "Cookies Policy",
    sustainability: "Sustainability",
    partners: "Partners",
    investors: "Investors",
    careers: "Careers",
    carriers: "Carriers",
    freight_forwarders: "Forwarders & Shippers",
    get_started: "Get started",
    tarif: "Pricing",
    explore_freight_forwarders_partners: "Explore Freight Forwarding Partners",
    carriers_protection_policy: "Carriers Protection Policy",
    pay_carrier_early: "Pay Carrier Early",
    api_integration: "API Integration",
    invite_your: "Invite your",
    our_open_positions: "Our open positions",
    contact_us: "Contact us",
    contact_text:
      "Do you have a question or want to get in touch with us? Fill out the form below to contact us.",
    contact_subtext: "You can also reach us at this email address:",
    where_to_find_us: "Where to find us",
    email: "Email",
    name: "Name",
    subject: "Subject",
    message: "Message",
    send: "Send",
    sending: "Sending...",
    share: "Share",
    copy_link: "Copy link",
    back_to_blog: "Back to blog",
    min_read: "min read",
    our_partners: "Our Partners",
    learn_more_cookies: "Learn more about our Cookies Policy",
    more_info_financial_services: "Learn more about Financial Services",
    integrations: "Integrations",
    "integrations.section": "Integrations",
    "integrations.title": "Connected with leading transport systems",
    "integrations.subtitle": "Selected ecosystem partners for telematics, TMS and logistics platforms",
    // About page
    "about.who_we_are.title": "Who we are",
    "about.our_sites.title": "Our sites",
    "about.our_sites.subtitle": "Two presences to better serve our customers",
    "about.visit": "Visit",
    "about.open_site": "Open site",
    "about.sites.global": "Global site",
    "about.sites.es": "Spain site",
    "about.our_values.title": "Our values",
    "about.values.integrity": "Integrity",
    "about.values.integrity_desc": "We build trust through transparency, accountability and consistent execution.",
    "about.values.innovation": "Innovation",
    "about.values.innovation_desc": "We continuously improve with pragmatic, data‑driven solutions.",
    "about.values.customer": "Customer focus",
    "about.values.customer_desc": "We optimize for real outcomes: faster cash cycles and fewer disputes.",
    "about.values.reliability": "Reliability",
    "about.values.reliability_desc": "We commit to stable, predictable systems and measurable SLAs.",
    "about.our_mission.title": "Our mission",
    "about.our_vision.title": "Our vision",
    "about.join_team.title": "Want to join the team?",
    "about.join_team.desc": "We’re hiring people passionate about transport, data and customer impact.",
    "about.join_team.cta": "See open roles",
    "about.who_we_are.highlights": "Highlights",
    "about.who.point1": "Clean, ethical and optimized funding",
    "about.who.point2": "Liquidity to accelerate growth",
    "about.who.point3": "Focus on reliable, high‑quality service",
    // About — Sites & addresses
    "about.address.ch": [
      "Fincargo SA",
      "Rue de L’Industrie 23",
      "1950 Sion",
      "Switzerland",
    ],
    "about.address.es": [
      "Fincargo Iberia SL",
      "Avenida Diagonal, 598",
      "08021 Barcelona",
      "Spain",
    ],
    "country.ch": "Switzerland",
    "country.es": "Spain",
    "about.map_alt": "Fincargo presence map",
    // Region banner
    "region.title.suggest": "Are you visiting from Belgium?",
    "region.title.chooser": "Select your region",
    "region.subtitle.suggest": "We have a Belgian version of Fincargo with local e-invoicing and financial services for transport.",
    "region.subtitle.chooser": "Visit our Belgian site for local e‑invoicing and financial services for transport, or stay on the global site.",
    "region.go_be": "Go to Fincargo Belgium",
    "region.stay": "Stay on this site",
    "region.choose_language": "Choose your language",
    "region.language.fr": "French",
    "region.language.en": "English",
    // Region switch (footer)
    "region.switch_be": "Switch to Belgium",
    "region.switch_global": "Switch to Europe",
  },
  es: {
    pricing: "Tarifas",
    demo: "Demo",
    register: "Registrar",
    login: "Entrar",
    for_carriers: "Para transportistas",
    services: "Servicios",
    benefits: "Beneficios",
    features: "Características",
    invite_your_freight_forwarder: "Invite a sus transitarios",
    invite_your_carriers: "Invite a sus transportistas",
    faq: "Preguntas",
    for_freight_forwarders: "Para transitarios",
    invite_your_subcontractors: "Invita a tus subcontratistas",
    company: "Empresa",
    about_us: "Sobre nosotros",
    contact: "Contacto",
    Confidentiality: "Confidencialidad y Seguridad",
    legal_notice: "Aviso legal",
    cookies: "Política de Cookies",
    sustainability: "Sostenibilidad",
    partners: "Socios",
    investors: "Inversores",
    careers: "Carrera",
    carriers: "TRANSPORTISTAS",
    freight_forwarders: "Transitarios y Cargadores",
    get_started: "Empezar",
    tarif: "Tarifas",
    explore_freight_forwarders_partners: "Explorar socios transitarios",
    carriers_protection_policy: "Política de protección para transportistas",
    pay_carrier_early: "Pagar al transportista anticipadamente",
    api_integration: "Integración de API",
    invite_your: "Invite a sus",
    our_open_positions: "Ofertas de empleo",
    contact_us: "Contáctenos",
    contact_text:
      "¿Tienes alguna pregunta o quieres ponerte en contacto con nosotros? Completa el formulario a continuación para contactarnos.",
    contact_subtext:
      "También puedes escribirnos a esta dirección de correo electrónico:",
    where_to_find_us: "Donde encontrarnos",
    email: "Correo electrónico",
    name: "Nombre",
    subject: "Asunto",
    message: "Mensaje",
    send: "Enviar",
    sending: "Enviando...",
    share: "Compartir",
    copy_link: "Copiar enlace",
    back_to_blog: "Volver al blog",
    min_read: "min de lectura",
    our_partners: "Nuestros socios",
    learn_more_cookies: "Más información sobre nuestra política de cookies",
    more_info_financial_services: "Más información sobre servicios financieros",
    integrations: "Integraciones",
    "integrations.section": "Integraciones",
    "integrations.title": "Conectado con los principales sistemas de transporte",
    "integrations.subtitle": "Socios del ecosistema seleccionados para telemática, TMS y plataformas logísticas",
    // About page
    "about.who_we_are.title": "Quiénes somos",
    "about.our_sites.title": "Nuestros sitios",
    "about.our_sites.subtitle": "Dos presencias para servir mejor a nuestros clientes",
    "about.visit": "Visitar",
    "about.open_site": "Abrir sitio",
    "about.sites.global": "Sitio global",
    "about.sites.es": "Sitio España",
    "about.our_values.title": "Nuestros valores",
    "about.values.integrity": "Integridad",
    "about.values.integrity_desc": "Construimos confianza con transparencia, responsabilidad y ejecución consistente.",
    "about.values.innovation": "Innovación",
    "about.values.innovation_desc": "Mejoramos continuamente con soluciones pragmáticas basadas en datos.",
    "about.values.customer": "Enfoque en el cliente",
    "about.values.customer_desc": "Optimizamos por resultados reales: ciclos de cobro más rápidos y menos disputas.",
    "about.values.reliability": "Fiabilidad",
    "about.values.reliability_desc": "Compromiso con sistemas estables, predecibles y SLA medibles.",
    "about.our_mission.title": "Nuestra misión",
    "about.our_vision.title": "Nuestra visión",
    "about.join_team.title": "¿Quieres unirte al equipo?",
    "about.join_team.desc": "Buscamos personas apasionadas por el transporte, los datos y el impacto en el cliente.",
    "about.join_team.cta": "Ver vacantes",
    "about.who_we_are.highlights": "Puntos clave",
    "about.who.point1": "Financiación limpia, ética y optimizada",
    "about.who.point2": "Liquidez para acelerar el crecimiento",
    "about.who.point3": "Enfoque en un servicio fiable y de alta calidad",
    // About — Sitios y direcciones
    "about.address.ch": [
      "Fincargo SA",
      "Rue de L’Industrie 23",
      "1950 Sion",
      "Suiza",
    ],
    "about.address.es": [
      "Fincargo Iberia SL",
      "Avenida Diagonal, 598",
      "08021 Barcelona",
      "España",
    ],
    "country.ch": "Suiza",
    "country.es": "España",
    "about.map_alt": "Mapa de presencia de Fincargo",
    // Region banner
    "region.title.suggest": "¿Nos visitas desde Bélgica?",
    "region.title.chooser": "Selecciona tu región",
    "region.subtitle.suggest": "Tenemos una versión belga de Fincargo con e‑facturación local y servicios financieros para el transporte.",
    "region.subtitle.chooser": "Visita nuestro sitio belga (e‑facturación local, servicios financieros) o quédate en el sitio global.",
    "region.go_be": "Ir a Fincargo Bélgica",
    "region.stay": "Permanecer en este sitio",
    "region.choose_language": "Elige tu idioma",
    "region.language.fr": "Francés",
    "region.language.en": "Inglés",
    // Region switch (footer)
    "region.switch_be": "Cambiar a Bélgica",
    "region.switch_global": "Cambiar a Europa",
  },
  fr: {
    pricing: "Tarifs",
    demo: "Démonstration",
    register: "S'inscrire",
    login: "Connexion",
    for_carriers: "Pour transporteurs",
    services: "Services",
    benefits: "Avantages",
    features: "Fonctionnalités",
    invite_your_freight_forwarder: "Invitez vos transitaires",
    invite_your_carriers: "Invitez vos transporteurs",
    faq: "FAQ",
    for_freight_forwarders: "Pour transitaires",
    invite_your_subcontractors: "Invitez vos sous-traitants",
    company: "Entreprise",
    about_us: "A propos de nous",
    contact: "Contact",
    Confidentiality: "Confidentialité et sécurité",
    legal_notice: "Mentions légales",
    cookies: "Politiques des cookies",
    sustainability: "Développement durable",
    partners: "Partenaires",
    investors: "Investisseurs",
    careers: "Carrière",
    carriers: "TRANSPORTEURS",
    freight_forwarders: "Transitaires & Chargeurs",
    get_started: "Commencer",
    tarif: "Tarifs",
    explore_freight_forwarders_partners:
      "Explorer les partenaires de transport",
    carriers_protection_policy: "Politique de protection des transporteurs",
    pay_carrier_early: "Payer le transporteur à l'avance",
    api_integration: "Intégration API",
    invite_your: "Invitez vos",
    our_open_positions: "Nos postes vacants",
    contact_us: "Contactez-nous",
    contact_text:
      "Vous avez une question ou souhaitez nous contacter? Remplissez le formulaire ci-dessous pour nous joindre",
    contact_subtext:
      "Vous pouvez également nous écrire à cette adresse e-mail :",
    where_to_find_us: "Où nous trouver",
    email: "Email",
    name: "Nom",
    subject: "Sujet",
    message: "Message",
    send: "Envoyer",
    sending: "Envoi en cours...",
    share: "Partager",
    copy_link: "Copier le lien",
    back_to_blog: "Retour au blog",
    min_read: "min de lecture",
    our_partners: "Nos partenaires",
    learn_more_cookies: "En savoir plus sur notre politique des cookies",
    more_info_financial_services: "En savoir plus sur les services financiers",
    integrations: "Intégrations",
    "integrations.section": "Intégrations",
    "integrations.title": "Connecté aux principaux systèmes de transport",
    "integrations.subtitle": "Partenaires de l'écosystème sélectionnés pour la télématique, les TMS et les plateformes logistiques",
    // About page
    "about.who_we_are.title": "Qui sommes‑nous",
    "about.our_sites.title": "Nos sites",
    "about.our_sites.subtitle": "Deux présences pour mieux servir nos clients",
    "about.visit": "Visiter",
    "about.open_site": "Ouvrir le site",
    "about.sites.global": "Site global",
    "about.sites.es": "Site Espagne",
    "about.our_values.title": "Nos valeurs",
    "about.values.integrity": "Intégrité",
    "about.values.integrity_desc": "Nous bâtissons la confiance par la transparence, la responsabilité et l’exécution.",
    "about.values.innovation": "Innovation",
    "about.values.innovation_desc": "Nous améliorons en continu avec des solutions pragmatiques guidées par la donnée.",
    "about.values.customer": "Orientation client",
    "about.values.customer_desc": "Nous optimisons les résultats concrets : cycles OTC plus courts, moins de litiges.",
    "about.values.reliability": "Fiabilité",
    "about.values.reliability_desc": "Nous visons des systèmes stables, prévisibles et des SLA mesurables.",
    "about.our_mission.title": "Notre mission",
    "about.our_vision.title": "Notre vision",
    "about.join_team.title": "Veux‑tu rejoindre l’équipe ?",
    "about.join_team.desc": "Nous recherchons des profils passionnés par le transport, la donnée et l’impact client.",
    "about.join_team.cta": "Voir nos offres",
    "about.who_we_are.highlights": "Nos engagements",
    "about.who.point1": "Financement propre, éthique et optimisé",
    "about.who.point2": "Liquidité pour accélérer la croissance",
    "about.who.point3": "Se concentrer sur un service fiable et de qualité",
    // About — Sites & adresses
    "about.address.ch": [
      "Fincargo SA",
      "Rue de L’Industrie 23",
      "1950 Sion",
      "Suisse",
    ],
    "about.address.es": [
      "Fincargo Iberia SL",
      "Avenida Diagonal, 598",
      "08021 Barcelone",
      "Espagne",
    ],
    "country.ch": "Suisse",
    "country.es": "Espagne",
    "about.map_alt": "Carte des implantations Fincargo",
    // Region banner
    "region.title.suggest": "Venez‑vous de Belgique ?",
    "region.title.chooser": "Sélectionnez votre région",
    "region.subtitle.suggest": "Nous avons une version belge de Fincargo avec e‑invoicing local et services financiers pour le transport.",
    "region.subtitle.chooser": "Visitez notre site belge (e‑invoicing local, services financiers), ou restez sur le site global.",
    "region.go_be": "Aller sur Fincargo Belgique",
    "region.stay": "Rester sur ce site",
    "region.choose_language": "Choisissez votre langue",
    "region.language.fr": "Français",
    "region.language.en": "Anglais",
    // Region switch (footer)
    "region.switch_be": "Basculer vers la Belgique",
    "region.switch_global": "Basculer vers l'Europe",
  },
  de: {
    pricing: "Preise",
    demo: "Demo",
    register: "Registrieren",
    login: "Anmelden",
    for_carriers: "Für Transporteure",
    services: "Dienstleistungen",
    benefits: "Vorteile",
    features: "Funktionen",
    invite_your_freight_forwarder: "Auftraggeber einladen",
    invite_your_carriers: "Subunternehmer einladen",
    faq: "FAQ",
    for_freight_forwarders: "Für Spediteure",
    invite_your_subcontractors: "Laden Sie Ihre Subunternehmer ein",
    company: "Unternehmen",
    about_us: "Über uns",
    contact: "Kontakt",
    Confidentiality: "Vertraulichkeit & Sicherheit",
    legal_notice: "Impressum",
    cookies: "Cookie-Richtlinien",
    sustainability: "Nachhaltigkeit",
    partners: "Partner",
    investors: "Investoren",
    careers: "Karriere",
    carriers: "TRANSPORTEURE",
    freight_forwarders: "Spediteure & Verlader",
    get_started: "Jetzt starten",
    tarif: "Preise",
    explore_freight_forwarders_partners: "Transportpartner erkunden",
    carriers_protection_policy: "Schutzrichtlinie für Transporteure",
    pay_carrier_early: "Zahle den Transporteur frühzeitig",
    api_integration: "API-Integration",
    our_open_positions: "Unsere offenen Stellen",
    contact_us: "Kontaktiere uns",
    contact_text:
      "Haben Sie eine Frage oder möchten Sie mit uns in Kontakt treten? Füllen Sie das untenstehende Formular aus, um uns zu erreichen.",
    contact_subtext:
      "Sie können uns auch unter dieser E-Mail-Adresse erreichen:",
    where_to_find_us: "Wo Sie uns finden",
    email: "Email",
    name: "Name",
    subject: "Betreff",
    message: "Nachricht",
    send: "Senden",
    sending: "Senden...",
    share: "Teilen",
    copy_link: "Link kopieren",
    back_to_blog: "Zurück zum Blog",
    min_read: "Min. Lesezeit",
    our_partners: "Unsere Partner",
    learn_more_cookies: "Mehr erfahren über unsere Cookie‑Richtlinie",
    more_info_financial_services: "Mehr erfahren über Finanzdienstleistungen",
    integrations: "Integrationen",
    "integrations.section": "Integrationen",
    "integrations.title": "Verbunden mit führenden Transportsystemen",
    "integrations.subtitle": "Ausgewählte Ökosystem‑Partner für Telematik, TMS und Logistikplattformen",
    // About page
    "about.who_we_are.title": "Wer wir sind",
    "about.our_sites.title": "Unsere Websites",
    "about.our_sites.subtitle": "Zwei Präsenzen für einen besseren Kundenservice",
    "about.visit": "Besuchen",
    "about.open_site": "Website öffnen",
    "about.sites.global": "Globale Website",
    "about.sites.es": "Website Spanien",
    "about.our_values.title": "Unsere Werte",
    "about.values.integrity": "Integrität",
    "about.values.integrity_desc": "Wir schaffen Vertrauen durch Transparenz, Verantwortung und konsequente Umsetzung.",
    "about.values.innovation": "Innovation",
    "about.values.innovation_desc": "Wir verbessern kontinuierlich mit pragmatischen, datengestützten Lösungen.",
    "about.values.customer": "Kundenfokus",
    "about.values.customer_desc": "Wir optimieren für echte Ergebnisse: schnellere Zahlungszyklen, weniger Streitfälle.",
    "about.values.reliability": "Zuverlässigkeit",
    "about.values.reliability_desc": "Wir setzen auf stabile, vorhersehbare Systeme und messbare SLAs.",
    "about.our_mission.title": "Unsere Mission",
    "about.our_vision.title": "Unsere Vision",
    "about.join_team.title": "Möchtest du dem Team beitreten?",
    "about.join_team.desc": "Wir suchen Menschen, die sich für Transport, Daten und Kundenerfolg begeistern.",
    "about.join_team.cta": "Offene Stellen",
    "about.who_we_are.highlights": "Schwerpunkte",
    "about.who.point1": "Saubere, ethische und optimierte Finanzierung",
    "about.who.point2": "Liquidität zur Beschleunigung des Wachstums",
    "about.who.point3": "Fokus auf zuverlässigen, hochwertigen Service",
    // About — Standorte & Adressen
    "about.address.ch": [
      "Fincargo SA",
      "Rue de L’Industrie 23",
      "1950 Sion",
      "Schweiz",
    ],
    "about.address.es": [
      "Fincargo Iberia SL",
      "Avenida Diagonal, 598",
      "08021 Barcelona",
      "Spanien",
    ],
    "country.ch": "Schweiz",
    "country.es": "Spanien",
    "about.map_alt": "Fincargo‑Standortkarte",
    // Region banner
    "region.title.suggest": "Besuchen Sie uns aus Belgien?",
    "region.title.chooser": "Wählen Sie Ihre Region",
    "region.subtitle.suggest": "Wir haben eine belgische Version von Fincargo mit lokaler E‑Rechnung und Finanzdienstleistungen für den Transport.",
    "region.subtitle.chooser": "Besuchen Sie unsere belgische Website (lokale E‑Rechnung, Finanzservices) oder bleiben Sie auf der globalen Seite.",
    "region.go_be": "Zur Fincargo‑Belgien‑Seite",
    "region.stay": "Auf dieser Seite bleiben",
    "region.choose_language": "Sprache auswählen",
    "region.language.fr": "Französisch",
    "region.language.en": "Englisch",
    // Region switch (footer)
    "region.switch_be": "Zu Belgien wechseln",
    "region.switch_global": "Zu Europa wechseln",
  },
} as const;
