export const GENERAL = {
  en: {
    pricing: "Pricing",
    demo: "Demo",
    register: "Sign Up",
    login: "Log In",
    for_carriers: "For carriers",
    services: "Services",
    benefits: "Benefits",
    invite_your_freight_forwarder: "Invite your forwarders",
    invite_your_carriers: "Invite your carriers",
    faq: "FAQ",
    for_freight_forwarders: "For freight forwarders",
    invite_your_subcontractors: "Invite your register",
    company: "Company",
    about_us: "About us",
    contact: "Contact",
    Confidentiality: "Confidentiality & Security",
    legal_notice: "Legal Notice",
    cookies: "Cookies Policy",
    sustainability: "Sustainability",
    partners: "Partners",
    investors: "Investors",
    careers: "Careers",
    carriers: "Carriers",
    freight_forwarders: "Forwarders & Shippers",
    get_started: "Get started",
    explore_freight_forwarders_partners: "Explore Freight Forwarding Partners",
    carriers_protection_policy: "Carriers Protection Policy",
    pay_carrier_early: "Pay Carrier Early",
    api_integration: "API Integration",
    invite_your: "Invite your",
    our_open_positions: "Our open positions",
    contact_us: "Contact us",
    contact_text:
      "Do you have a question or want to get in touch with us? Fill out the form below to contact us.",
    contact_subtext: "You can also reach us at this email address:",
    where_to_find_us: "Where to find us",
    email: "Email",
    name: "Name",
    subject: "Subject",
    message: "Message",
    send: "Send",
    sending: "Sending...",
    share: "Share",
    copy_link: "Copy link",
    back_to_blog: "Back to blog",
  },
  es: {
    pricing: "Tarifas",
    demo: "Demo",
    register: "Registrar",
    login: "Entrar",
    for_carriers: "Para transportistas",
    services: "Servicios",
    benefits: "Beneficios",
    invite_your_freight_forwarder: "Invite a sus transitarios",
    invite_your_carriers: "Invite a sus transportistas",
    faq: "Preguntas",
    for_freight_forwarders: "Para transitarios",
    invite_your_subcontractors: "Invita a tus subcontratistas",
    company: "Empresa",
    about_us: "Sobre nosotros",
    contact: "Contacto",
    Confidentiality: "Confidencialidad y Seguridad",
    legal_notice: "Aviso legal",
    cookies: "Política de Cookies",
    sustainability: "Sostenibilidad",
    partners: "Socios",
    investors: "Inversores",
    careers: "Carrera",
    carriers: "TRANSPORTISTAS",
    freight_forwarders: "Transitarios y Cargadores",
    get_started: "Empezar",
    explore_freight_forwarders_partners: "Explorar socios transitarios",
    carriers_protection_policy: "Política de protección para transportistas",
    pay_carrier_early: "Pagar al transportista anticipadamente",
    api_integration: "Integración de API",
    invite_your: "Invite a sus",
    our_open_positions: "Ofertas de empleo",
    contact_us: "Contáctenos",
    contact_text:
      "¿Tienes alguna pregunta o quieres ponerte en contacto con nosotros? Completa el formulario a continuación para contactarnos.",
    contact_subtext:
      "También puedes escribirnos a esta dirección de correo electrónico:",
    where_to_find_us: "Donde encontrarnos",
    email: "Correo electrónico",
    name: "Nombre",
    subject: "Asunto",
    message: "Mensaje",
    send: "Enviar",
    sending: "Enviando...",
    share: "Compartir",
    copy_link: "Copiar enlace",
    back_to_blog: "Volver al blog",
  },
  fr: {
    pricing: "Tarifs",
    demo: "Démonstration",
    register: "S'inscrire",
    login: "Connexion",
    for_carriers: "Pour transporteurs",
    services: "Services",
    benefits: "Avantages",
    invite_your_freight_forwarder: "Invitez vos transitaires",
    invite_your_carriers: "Invitez vos transporteurs",
    faq: "FAQ",
    for_freight_forwarders: "Pour transitaires",
    invite_your_subcontractors: "Invitez vos sous-traitants",
    company: "Entreprise",
    about_us: "A propos de nous",
    contact: "Contact",
    Confidentiality: "Confidentialité et sécurité",
    legal_notice: "Mentions légales",
    cookies: "Politiques des cookies",
    sustainability: "Développement durable",
    partners: "Partenaires",
    investors: "Investisseurs",
    careers: "Carrière",
    carriers: "TRANSPORTEURS",
    freight_forwarders: "Transitaires & Chargeurs",
    get_started: "Commencer",
    explore_freight_forwarders_partners:
      "Explorer les partenaires de transport",
    carriers_protection_policy: "Politique de protection des transporteurs",
    pay_carrier_early: "Payer le transporteur à l'avance",
    api_integration: "Intégration API",
    invite_your: "Invitez vos",
    our_open_positions: "Nos postes vacants",
    contact_us: "Contactez-nous",
    contact_text:
      "Vous avez une question ou souhaitez nous contacter? Remplissez le formulaire ci-dessous pour nous joindre",
    contact_subtext:
      "Vous pouvez également nous écrire à cette adresse e-mail :",
    where_to_find_us: "Où nous trouver",
    email: "Email",
    name: "Nom",
    subject: "Sujet",
    message: "Message",
    send: "Envoyer",
    sending: "Envoi en cours...",
    share: "Partager",
    copy_link: "Copier le lien",
    back_to_blog: "Retour au blog",
  },
  de: {
    pricing: "Preise",
    demo: "Demo",
    register: "Registrieren",
    login: "Anmelden",
    for_carriers: "Für Transporteure",
    services: "Dienstleistungen",
    benefits: "Vorteile",
    invite_your_freight_forwarder: "Auftraggeber einladen",
    invite_your_carriers: "Subunternehmer einladen",
    faq: "FAQ",
    for_freight_forwarders: "Für Spediteure",
    invite_your_subcontractors: "Laden Sie Ihre Subunternehmer ein",
    company: "Unternehmen",
    about_us: "Über uns",
    contact: "Kontakt",
    Confidentiality: "Vertraulichkeit & Sicherheit",
    legal_notice: "Impressum",
    cookies: "Cookie-Richtlinien",
    sustainability: "Nachhaltigkeit",
    partners: "Partner",
    investors: "Investoren",
    careers: "Karriere",
    carriers: "TRANSPORTEURE",
    freight_forwarders: "Spediteure & Verlader",
    get_started: "Jetzt starten",
    explore_freight_forwarders_partners: "Transportpartner erkunden",
    carriers_protection_policy: "Schutzrichtlinie für Transporteure",
    pay_carrier_early: "Zahle den Transporteur frühzeitig",
    api_integration: "API-Integration",
    our_open_positions: "Unsere offenen Stellen",
    contact_us: "Kontaktiere uns",
    contact_text:
      "Haben Sie eine Frage oder möchten Sie mit uns in Kontakt treten? Füllen Sie das untenstehende Formular aus, um uns zu erreichen.",
    contact_subtext:
      "Sie können uns auch unter dieser E-Mail-Adresse erreichen:",
    where_to_find_us: "Wo Sie uns finden",
    email: "Email",
    name: "Name",
    subject: "Betreff",
    message: "Nachricht",
    send: "Senden",
    sending: "Senden...",
    share: "Teilen",
    copy_link: "Link kopieren",
    back_to_blog: "Zurück zum Blog",
  },
} as const;
