export const HERO = {
  en: {
    "hero.bank_label": "Execution Truth",
    "hero.efti_label": "Fiscal Truth",
    "hero.vida_lablel": "Liquidity Truth",
    "hero.all_label": "Insight Truth",
    "hero.see_demo": "See demo",
    "hero.more_info": "More info",
    "hero.b2b.label": "B2B Mandate Timing",
    "hero.model.lable": "Model",
    "hero.country.data.1": ["Italy", "Jan 2019", "3-corner"],
    "hero.country.data.2": ["Romania", "July 2024", "3-corner"],
    "hero.country.data.3": ["Belgium", "Jan 2026", "4-corner"],
    "hero.country.data.4": ["Poland", "February 2026", "3-corner"],
    "hero.country.data.5": ["France", "Sept 2026", "5-corner"],
  },
  es: {
    "hero.bank_label": "Verdad de ejecución",
    "hero.efti_label": "Verdad fiscal",
    "hero.vida_lablel": "Verdad de liquidez",
    "hero.all_label": "Verdad de insight",
    "hero.see_demo": "Ver demostración",
    "hero.more_info": "Más información",
    "hero.b2b.label": "Plazos del mandato B2B",
    "hero.model.lable": "Modelo",
    "hero.country.data.1": ["Italia", "Ene 2019", "3-esquinas"],
    "hero.country.data.2": ["Rumania", "Jul 2024", "3-esquinas"],
    "hero.country.data.3": ["Bélgica", "Ene 2026", "4-esquinas"],
    "hero.country.data.4": ["Polonia", "Feb 2026", "3-esquinas"],
    "hero.country.data.5": ["Francia", "Sep 2026", "5-esquinas"],
  },

  fr: {
    "hero.bank_label": "Vérité d'exécution",
    "hero.efti_label": "Vérité fiscale",
    "hero.vida_lablel": "Vérité de liquidité",
    "hero.all_label": "Vérité d'insight",
    "hero.see_demo": "Voir la démo",
    "hero.more_info": "En savoir plus",
    "hero.b2b.label": "Délais du mandat B2B",
    "hero.model.lable": "Modèle",
    "hero.country.data.1": ["Italie", "Jan 2019", "3 coins"],
    "hero.country.data.2": ["Roumanie", "Juil 2024", "3 coins"],
    "hero.country.data.3": ["Belgique", "Jan 2026", "4 coins"],
    "hero.country.data.4": ["Pologne", "Fév 2026", "3 coins"],
    "hero.country.data.5": ["France", "Sep 2026", "5 coins"],
  },

  de: {
    "hero.bank_label": "Ausführungswahrheit",
    "hero.efti_label": "Fiskalwahrheit",
    "hero.vida_lablel": "Liquiditätswahrheit",
    "hero.all_label": "Erkenntniswahrheit",
    "hero.see_demo": "Demo ansehen",
    "hero.more_info": "Mehr Infos",
    "hero.b2b.label": "B2B-Mandatsfristen",
    "hero.model.lable": "Modell",
    "hero.country.data.1": ["Italien", "Jan 2019", "3-Ecken"],
    "hero.country.data.2": ["Rumänien", "Jul 2024", "3-Ecken"],
    "hero.country.data.3": ["Belgien", "Jan 2026", "4-Ecken"],
    "hero.country.data.4": ["Polen", "Feb 2026", "3-Ecken"],
    "hero.country.data.5": ["Frankreich", "Sep 2026", "5-Ecken"],
  },
} as const;
