export const INTEGRATION = {
  en: {
    "integration.title": "Feature-rich Integration",
    "integration.subtitle":
      "Go live in weeks with unified, reliable connectivity to ERP, TMS, and Accounting—no CSVs, full write-back, enterprise-grade controls.",
    "integration.section1_title": "Key features",
    "integration.section1_subtitle1": "Connectors (ERP/TMS/Accounting)",
    "integration.section1.point1": [
      "Unified, resilient connectivity; no manual CSVs",
      "REST/GraphQL APIs, webhooks; SFTP fallback",
      "OAuth/SSO, retries & queuing, idempotent delta sync",
      "Multi-entity and multi-locale support",
    ],
    "integration.section1_subtitle2": "Mapping & Normalization",
    "integration.section1.point2": [
      "Canonical data model and code-list alignment",
      "Validation rules with AI-assisted mapping suggestions",
      "Field-level transforms with version control",
      "Cleaner data, fewer mapping errors, faster onboarding",
    ],
    "integration.section1_subtitle3": "Write-Back Coverage",
    "integration.section1.point3": [
      "Keep ERP/TMS/Accounting the source of truth",
      "Bi-directional write-back: IDs/series (e.g., ATCUD/QR), ACK/status, due dates, FX, AR/AP postings, evidence links",
      "Reconciliation reports and coverage SLAs",
      "Less month-end reconciliation, one truth across systems",
    ],
    "integration.section1_subtitle4": "Observability & SLAs",
    "integration.section1.point4": [
      "End-to-end dashboards (flow, latency, retries)",
      "Proactive alerting, runbooks, safe rollbacks (CI/CD)",
      "Uptime/MTTR SLAs for predictable reliability",
      "Issues found and fixed before users notice",
    ],
    "integration.section1_subtitle5": " Access & Compliance",
    "integration.section1.point5": [
      "RBAC, least-privilege access, audit logs",
      "Encryption in transit/at rest, IP allow-listing",
      "GDPR alignment, data-residency options, retention & key management",
      "Audit-ready posture and reduced risk",
    ],
    "integration.section2.title": "Benefits",
    "integration.section2.carrier.title": "Carriers",
    "integration.section2.carrier.point": [
      "Connect once; operate across systems",
      "Replace CSVs with real-time exchange",
      "Normalize data; reduce back-office errors",
      "Security and compliance built-in",
    ],
    "integration.section2.forwarder.title": "Forwarders & Shippers",
    "integration.section2.forwarder.point": [
      "One source of truth via write-back",
      "Accelerate go-lives with prebuilt connectors",
      "Reliable flows with proactive observability",
      "Audit-ready posture and evidence retention",
    ],
  },
  fr: {
    "integration.title": "Intégration riche en fonctionnalités",
    "integration.subtitle":
      "Mettez en service en quelques semaines une connectivité unifiée et fiable avec les ERP, TMS et la comptabilité—sans CSV, avec écriture complète, et des contrôles de niveau entreprise.",
    "integration.section1_title": "Fonctionnalités clés",
    "integration.section1_subtitle1": "Connecteurs (ERP/TMS/Comptabilité)",
    "integration.section1.point1": [
      "Connectivité unifiée et résiliente; pas de CSV manuels",
      "APIs REST/GraphQL, webhooks; repli SFTP",
      "OAuth/SSO, réessais & mise en file d'attente, synchronisation delta idempotente",
      "Support multi-entité et multi-locale",
    ],
    "integration.section1_subtitle2": "Mappage & Normalisation",
    "integration.section1.point2": [
      "Modèle de données canonique et alignement des listes de codes",
      "Règles de validation avec suggestions de mappage assistées par IA",
      "Transformations au niveau des champs avec contrôle de version",
      "Données plus propres, moins d'erreurs de mappage, intégration plus rapide",
    ],
    "integration.section1_subtitle3": "Couverture d'écriture",
    "integration.section1.point3": [
      "Gardez l'ERP/TMS/Comptabilité comme source de vérité",
      "Écriture bidirectionnelle : IDs/séries (par ex., ATCUD/QR), ACK/statut, dates d'échéance, FX, écritures AR/AP, liens de preuve",
      "Rapports de réconciliation et SLA de couverture",
      "Moins de réconciliations de fin de mois, une seule vérité à travers les systèmes",
    ],
    "integration.section1_subtitle4": "Observabilité & SLA",
    "integration.section1.point4": [
      "Tableaux de bord de bout en bout (flux, latence, réessais)",
      "Alertes proactives, runbooks, retours en arrière sûrs (CI/CD)",
      "SLA de disponibilité/MTTR pour une fiabilité prévisible",
      "Problèmes trouvés et corrigés avant que les utilisateurs ne les remarquent",
    ],
    "integration.section1_subtitle5": "Accès & Conformité",
    "integration.section1.point5": [
      "RBAC, accès au moindre privilège, journaux d'audit",
      "Chiffrement en transit/au repos, liste d'autorisation IP",
      "Alignement GDPR, options de résidence des données, gestion de la rétention & des clés",
      "Posture prête pour l'audit et risque réduit",
    ],
    "integration.section2.title": "Avantages",
    "integration.section2.carrier.title": "Transporteurs",
    "integration.section2.carrier.point": [
      "Connectez une fois; opérez à travers les systèmes",
      "Remplacez les CSV par un échange en temps réel",
      "Normalisez les données; réduisez les erreurs de back-office",
      "Sécurité et conformité intégrées",
    ],
    "integration.section2.forwarder.title": "Transitaires & Expéditeurs",
    "integration.section2.forwarder.point": [
      "Une source de vérité via l'écriture",
      "Accélérez les mises en service avec des connecteurs préconstruits",
      "Flux fiables avec une observabilité proactive",
      "Posture prête pour l'audit et rétention des preuves",
    ],
  },
  es: {
    "integration.title": "Integración rica en funciones",
    "integration.subtitle":
      "Póngase en marcha en semanas con una conectividad unificada y confiable con ERP, TMS y Contabilidad—sin CSV, con escritura completa y controles de nivel empresarial.",
    "integration.section1_title": "Características clave",
    "integration.section1_subtitle1": "Conectores (ERP/TMS/Contabilidad)",
    "integration.section1.point1": [
      "Conectividad unificada y resistente; sin CSV manuales",
      "APIs REST/GraphQL, webhooks; respaldo SFTP",
      "OAuth/SSO, reintentos y encolamiento, sincronización delta idempotente",
      "Soporte multi-entidad y multi-local",
    ],
    "integration.section1_subtitle2": "Mapeo y Normalización",
    "integration.section1.point2": [
      "Modelo de datos canónico y alineación de listas de códigos",
      "Reglas de validación con sugerencias de mapeo asistidas por IA",
      "Transformaciones a nivel de campo con control de versiones",
      "Datos más limpios, menos errores de mapeo, incorporación más rápida",
    ],
    "integration.section1_subtitle3": "Cobertura de Escritura",
    "integration.section1.point3": [
      "Mantenga ERP/TMS/Contabilidad como la fuente de la verdad",
      "Escritura bidireccional: IDs/series (p.ej., ATCUD/QR), ACK/estado, fechas de vencimiento, FX, publicaciones AR/AP, enlaces de evidencia",
      "Informes de conciliación y SLA de cobertura",
      "Menos conciliación de fin de mes, una sola verdad en todos los sistemas",
    ],
    "integration.section1_subtitle4": "Observabilidad y SLA",
    "integration.section1.point4": [
      "Paneles de extremo a extremo (flujo, latencia, reintentos)",
      "Alertas proactivas, runbooks, retrocesos seguros (CI/CD)",
      "SLA de tiempo de actividad/MTTR para una confiabilidad predecible",
      "Problemas encontrados y solucionados antes de que los usuarios los noten",
    ],
    "integration.section1_subtitle5": "Acceso y Cumplimiento",
    "integration.section1.point5": [
      "RBAC, acceso de menor privilegio, registros de auditoría",
      "Cifrado en tránsito/en reposo, lista de permitidos IP",
      "Alineación GDPR, opciones de residencia de datos, retención y gestión de claves",
      "Postura lista para auditoría y riesgo reducido",
    ],
    "integration.section2.title": "Beneficios",
    "integration.section2.carrier.title": "Transportistas",
    "integration.section2.carrier.point": [
      "Conéctese una vez; opere a través de sistemas",
      "Reemplace los CSV con intercambio en tiempo real",
      "Normalice los datos; reduzca los errores de back-office",
      "Seguridad y cumplimiento integrados",
    ],
    "integration.section2.forwarder.title": "Transitarios y Remitentes",
    "integration.section2.forwarder.point": [
      "Una fuente de verdad a través de la escritura",
      "Acelere las puestas en marcha con conectores preconstruidos",
      "Flujos confiables con observabilidad proactiva",
      "Postura lista para auditoría y retención de evidencia",
    ],
  },
  de: {
    "integration.title": "Funktionsreiche Integration",
    "integration.subtitle":
      "Inbetriebnahme in Wochen mit einheitlicher, zuverlässiger Konnektivität zu ERP, TMS und Buchhaltung—keine CSVs, vollständige Rückschreibung, unternehmensgerechte Kontrollen.",
    "integration.section1_title": "Hauptmerkmale",
    "integration.section1_subtitle1": "Konnektoren (ERP/TMS/Buchhaltung)",
    "integration.section1.point1": [
      "Einheitliche, widerstandsfähige Konnektivität; keine manuellen CSVs",
      "REST/GraphQL APIs, Webhooks; SFTP-Fallback",
      "OAuth/SSO, Wiederholungen & Warteschlangen, idempotente Delta-Synchronisierung",
      "Unterstützung für mehrere Einheiten und mehrere Sprachen",
    ],
    "integration.section1_subtitle2": "Mapping & Normalisierung",
    "integration.section1.point2": [
      "Kanonisches Datenmodell und Code-Listen-Ausrichtung",
      "Validierungsregeln mit KI-gestützten Mapping-Vorschlägen",
      "Feldspezifische Transformationen mit Versionskontrolle",
      "Sauberere Daten, weniger Mapping-Fehler, schnellere Einführung",
    ],
    "integration.section1_subtitle3": "Rückschreibungsabdeckung",
    "integration.section1.point3": [
      "Behalten Sie ERP/TMS/Buchhaltung als Quelle der Wahrheit bei",
      "Bidirektionale Rückschreibung: IDs/Serien (z.B. ATCUD/QR), ACK/Status, Fälligkeitstermine, FX, AR/AP Buchungen, Beleglinks",
      "Abstimmungsberichte und Abdeckungs-SLAs",
      "Weniger Monatsabschlussabstimmungen, eine Wahrheit über alle Systeme hinweg",
    ],
    "integration.section1_subtitle4": "Beobachtbarkeit & SLAs",
    "integration.section1.point4": [
      "End-to-End-Dashboards (Fluss, Latenz, Wiederholungen)",
      "Proaktive Alarmierung, Runbooks, sichere Rollbacks (CI/CD)",
      "Uptime/MTTR SLAs für vorhersehbare Zuverlässigkeit",
      "Probleme werden gefunden und behoben, bevor Benutzer sie bemerken",
    ],
    "integration.section1_subtitle5": "Zugriff & Compliance",
    "integration.section1.point5": [
      "RBAC, Least-Privilege-Zugriff, Audit-Logs",
      "Verschlüsselung während der Übertragung/im Ruhezustand, IP-Whitelist",
      "GDPR-Ausrichtung, Datenresidenzoptionen, Aufbewahrungs- & Schlüsselverwaltung",
      "Audit-bereite Haltung und reduziertes Risiko",
    ],
    "integration.section2.title": "Vorteile",
    "integration.section2.carrier.title": "Spediteure",
    "integration.section2.carrier.point": [
      "Einmal verbinden; über Systeme hinweg arbeiten",
      "Ersetzen Sie CSVs durch Echtzeitaustausch",
      "Daten normalisieren; weniger Back-Office-Fehler",
      "Sicherheit und Compliance integriert",
    ],
    "integration.section2.forwarder.title": "Frachtführer & Verlader",
    "integration.section2.forwarder.point": [
      "Eine Quelle der Wahrheit durch Rückschreibung",
      "Beschleunigen Sie die Inbetriebnahme mit vorgefertigten Konnektoren",
      "Zuverlässige Abläufe mit proaktiver Beobachtbarkeit",
      "Audit-bereite Haltung und Belegaufbewahrung",
    ],
  },
} as const;
