export const KPIS = {
  en: {
    "kpis.home.titles": [
      "24 Hours",
      "90 → 1 Days",
      "99.5% Approval",
      "70% Less Admin",
      "0 Hidden Fees",
    ],
    "kpis.home.desc": [
      "Cash approval, fast liquidity when it’s needed most",
      "DSO acceleration with instant payment on delivery",
      "First-pass invoice acceptance with clean data capture",
      "Automation reduces workload and errors",
      "Transparent pricing and fair access to capital",
    ],
    "kpis.about.titles": [
      "8+ Countries",
      "1M+ Shipments",
      "100% AML/KYC",
      "99.9% Uptime",
      "< 1 Second",
    ],
    "kpis.about.desc": [
      "Solution deployed and compliant across Asia and Europe",
      "Technology proven on millions of transactions yearly",
      "Integrated compliance on every transaction",
      "Bank-grade infrastructure for uninterrupted service",
      "AI risk detection before funds are released",
    ],
  },
  fr: {
    "kpis.home.titles": [
      "24 Heures",
      "90 → 1 Jours",
      "99,5% d’approbation",
      "70% d’administration en moins",
      "0 frais cachés",
    ],
    "kpis.home.desc": [
      "Approbation de trésorerie, liquidité rapide quand c’est le plus nécessaire",
      "Accélération du DSO avec paiement immédiat à la livraison",
      "Acceptation au premier passage grâce à une capture de données propre",
      "L’automatisation réduit la charge et les erreurs",
      "Tarification transparente et accès équitable au capital",
    ],
    "kpis.about.titles": [
      "8+ Pays",
      "1M+ Expéditions",
      "100% AML/KYC",
      "99,9% Disponibilité",
      "< 1 Seconde",
    ],
    "kpis.about.desc": [
      "Solution déployée et conforme en Asie et en Europe",
      "Technologie éprouvée sur des millions de transactions par an",
      "Conformité intégrée à chaque transaction",
      "Infrastructure de niveau bancaire pour un service ininterrompu",
      "Détection de risque par IA avant le déblocage des fonds",
    ],
  },
  es: {
    "kpis.home.titles": [
      "24 Horas",
      "90 → 1 Días",
      "99,5% Aprobación",
      "70% Menos Admin",
      "0 Tarifas Ocultas",
    ],
    "kpis.home.desc": [
      "Aprobación de liquidez, efectivo rápido cuando más se necesita",
      "Aceleración del DSO con pago instantáneo en la entrega",
      "Aceptación en el primer intento con captura de datos limpia",
      "La automatización reduce la carga y los errores",
      "Precios transparentes y acceso justo al capital",
    ],
    "kpis.about.titles": [
      "8+ Países",
      "1M+ Envíos",
      "100% AML/KYC",
      "99,9% Disponibilidad",
      "< 1 Segundo",
    ],
    "kpis.about.desc": [
      "Solución desplegada y conforme en Asia y Europa",
      "Tecnología probada en millones de transacciones anuales",
      "Cumplimiento integrado en cada transacción",
      "Infraestructura de nivel bancario para servicio ininterrumpido",
      "Detección de riesgo con IA antes de liberar fondos",
    ],
  },
  de: {
    "kpis.home.titles": [
      "24 Stunden",
      "90 → 1 Tage",
      "99,5% Genehmigung",
      "70% Weniger Admin",
      "0 Versteckte Gebühren",
    ],
    "kpis.home.desc": [
      "Liquiditätsfreigabe, schnelle Mittel wenn sie am nötigsten sind",
      "DSO‑Beschleunigung mit sofortiger Zahlung bei Lieferung",
      "Erstfreigabe von Rechnungen dank sauberer Datenerfassung",
      "Automatisierung reduziert Arbeitsaufwand und Fehler",
      "Transparente Preise und fairer Zugang zu Kapital",
    ],
    "kpis.about.titles": [
      "8+ Länder",
      "1M+ Sendungen",
      "100% AML/KYC",
      "99,9% Verfügbarkeit",
      "< 1 Sekunde",
    ],
    "kpis.about.desc": [
      "Lösung in Asien und Europa ausgerollt und konform",
      "Technologie bewährt bei Millionen Transaktionen pro Jahr",
      "Integrierte Compliance bei jeder Transaktion",
      "Banktaugliche Infrastruktur für unterbrechungsfreien Betrieb",
      "KI‑Risikoprüfung bevor Mittel freigegeben werden",
    ],
  },
  nl: {
    "kpis.home.titles": [
      "24 Uur",
      "90 → 1 Dagen",
      "99,5% Goedkeuring",
      "70% Minder Admin",
      "0 Verborgen Kosten",
    ],
    "kpis.home.desc": [
      "Snelle liquiditeit wanneer het het meest nodig is",
      "DSO‑versnelling met directe betaling bij levering",
      "Eerste‑keer acceptatie dankzij schone gegevensvastlegging",
      "Automatisering vermindert werkdruk en fouten",
      "Transparante prijzen en eerlijke toegang tot kapitaal",
    ],
    "kpis.about.titles": [
      "8+ Landen",
      "1M+ Zendingen",
      "100% AML/KYC",
      "99,9% Uptime",
      "< 1 Seconde",
    ],
    "kpis.about.desc": [
      "Oplossing uitgerold en conform in Azië en Europa",
      "Technologie bewezen op miljoenen transacties per jaar",
      "Geïntegreerde compliance bij elke transactie",
      "Bankwaardige infrastructuur voor ononderbroken service",
      "AI‑risicodetectie voordat geld wordt vrijgegeven",
    ],
  },
} as const;
