export const KPIS = {
  en: {
    "kpis.home.titles": [
      "24 Hours",
      "90 → 1 Days",
      "99.5% Approval",
      "70% Less Admin",
      "0 Hidden Fees",
    ],
    "kpis.home.desc": [
      "Liquidity truth — verified invoices unlocking cash in under 24 hours",
      "Economic truth — execution data collapsing DSO from 90 to 1 day",
      "Fiscal truth — first-pass invoice acceptance through compliant e-Invoicing",
      "Execution truth — digital capture eliminating manual paperwork and rework",
      "Continuity truth — transparent pricing, no surprises in your cash flow",
    ],
    "kpis.about.titles": [
      "8+ Countries",
      "1M+ Shipments",
      "100% AML/KYC",
      "99.9% Uptime",
      "< 1 Second",
    ],
    "kpis.about.desc": [
      "Solution deployed and compliant across Asia and Europe",
      "Technology proven on millions of transactions yearly",
      "Integrated compliance on every transaction",
      "Bank-grade infrastructure for uninterrupted service",
      "AI risk detection before funds are released",
    ],
  },
  fr: {
    "kpis.home.titles": [
      "24 Heures",
      "90 → 1 Jours",
      "99,5% d'approbation",
      "70% d'administration en moins",
      "0 frais cachés",
    ],
    "kpis.home.desc": [
      "Vérité de liquidité — factures vérifiées débloquant des liquidités en moins de 24 heures",
      "Vérité économique — données d'exécution réduisant le DSO de 90 à 1 jour",
      "Vérité fiscale — acceptation au premier passage via une e-facturation conforme",
      "Vérité d'exécution — capture numérique éliminant les tâches manuelles et les reprises",
      "Vérité de continuité — tarification transparente, sans surprise dans votre flux de trésorerie",
    ],
    "kpis.about.titles": [
      "8+ Pays",
      "1M+ Expéditions",
      "100% AML/KYC",
      "99,9% Disponibilité",
      "< 1 Seconde",
    ],
    "kpis.about.desc": [
      "Solution déployée et conforme en Asie et en Europe",
      "Technologie éprouvée sur des millions de transactions par an",
      "Conformité intégrée à chaque transaction",
      "Infrastructure de niveau bancaire pour un service ininterrompu",
      "Détection de risque par IA avant le déblocage des fonds",
    ],
  },
  es: {
    "kpis.home.titles": [
      "24 Horas",
      "90 → 1 Días",
      "99,5% Aprobación",
      "70% Menos Admin",
      "0 Tarifas Ocultas",
    ],
    "kpis.home.desc": [
      "Verdad de liquidez — facturas verificadas que desbloquean efectivo en menos de 24 horas",
      "Verdad económica — datos de ejecución que reducen el DSO de 90 a 1 día",
      "Verdad fiscal — aceptación en el primer intento mediante e-facturación conforme",
      "Verdad de ejecución — captura digital que elimina el papeleo manual y las correcciones",
      "Verdad de continuidad — precios transparentes, sin sorpresas en tu flujo de caja",
    ],
    "kpis.about.titles": [
      "8+ Países",
      "1M+ Envíos",
      "100% AML/KYC",
      "99,9% Disponibilidad",
      "< 1 Segundo",
    ],
    "kpis.about.desc": [
      "Solución desplegada y conforme en Asia y Europa",
      "Tecnología probada en millones de transacciones anuales",
      "Cumplimiento integrado en cada transacción",
      "Infraestructura de nivel bancario para servicio ininterrumpido",
      "Detección de riesgo con IA antes de liberar fondos",
    ],
  },
  de: {
    "kpis.home.titles": [
      "24 Stunden",
      "90 → 1 Tage",
      "99,5% Genehmigung",
      "70% Weniger Admin",
      "0 Versteckte Gebühren",
    ],
    "kpis.home.desc": [
      "Liquiditätswahrheit — verifizierte Rechnungen, die Liquidität in unter 24 Stunden freisetzen",
      "Wirtschaftswahrheit — Ausführungsdaten, die DSO von 90 auf 1 Tag verkürzen",
      "Fiskalwahrheit — Erstakzeptanz durch konforme e-Rechnungsstellung",
      "Ausführungswahrheit — digitale Erfassung eliminiert manuellen Papierkram und Nacharbeit",
      "Kontinuitätswahrheit — transparente Preise, keine Überraschungen im Cashflow",
    ],
    "kpis.about.titles": [
      "8+ Länder",
      "1M+ Sendungen",
      "100% AML/KYC",
      "99,9% Verfügbarkeit",
      "< 1 Sekunde",
    ],
    "kpis.about.desc": [
      "Lösung in Asien und Europa ausgerollt und konform",
      "Technologie bewährt bei Millionen Transaktionen pro Jahr",
      "Integrierte Compliance bei jeder Transaktion",
      "Banktaugliche Infrastruktur für unterbrechungsfreien Betrieb",
      "KI‑Risikoprüfung bevor Mittel freigegeben werden",
    ],
  },
  nl: {
    "kpis.home.titles": [
      "24 Uur",
      "90 → 1 Dagen",
      "99,5% Goedkeuring",
      "70% Minder Admin",
      "0 Verborgen Kosten",
    ],
    "kpis.home.desc": [
      "Liquiditeitswahrheid — geverifieerde facturen die liquiditeit vrijmaken binnen 24 uur",
      "Economische waarheid — uitvoeringsdata die DSO terugbrengt van 90 naar 1 dag",
      "Fiscale waarheid — eerste-keer acceptatie via conforme e-facturering",
      "Uitvoeringswahrheid — digitale vastlegging elimineert handmatig papierwerk",
      "Continuïteitswahrheid — transparante prijzen, geen verrassingen in uw cashflow",
    ],
    "kpis.about.titles": [
      "8+ Landen",
      "1M+ Zendingen",
      "100% AML/KYC",
      "99,9% Uptime",
      "< 1 Seconde",
    ],
    "kpis.about.desc": [
      "Oplossing uitgerold en conform in Azië en Europa",
      "Technologie bewezen op miljoenen transacties per jaar",
      "Geïntegreerde compliance bij elke transactie",
      "Bankwaardige infrastructuur voor ononderbroken service",
      "AI‑risicodetectie voordat geld wordt vrijgegeven",
    ],
  },
} as const;
