export const PRICINGS = {
  en: {
    "pricing.title": "Transparent Pricing for Road Transportation",
    "picing.description":
      "Choose the plan that fits your business size. All plans include our four core services: e-CMR/e-PoD, e-Invoicing, freight audit, and factoring.",
    "pricing.features.title": "Features",
    "pricing.feature1": "e-CMR & e-PoD",
    "pricing.feature2": "Invoice Verification",
    "pricing.feature3": "e-Invoicing",
    "pricing.feature4": "Factoring",
    "pricing.feature5": "Support",
    "pricing.feature6": "Transactional Fee",
    "pricing.feature7": "Integration & Calibration",
    "pricing.currency": "CHF",
    "priciing.time": "/month/user",
    "pricing.starter.title": "Starter",
    "pricing.starter.description": "Carriers & small forwarders",
    "pricing.starter.price": "199",
    "pricing.starter.features1": "10 docs/mo",
    "pricing.starter.features2": "Up to 50K CHF/month",
    "pricing.starter.features3": "75 docs/mo",
    "pricing.starter.features4": ".10–0.15%/day + 20CHF/service fee",
    "pricing.starter.features5": "Iris Support",
    "pricing.starter.features6": "3CHF/doc (service initiator)",
    "pricing.starter.features7": "None",
    "pricing.growth.title": "Growth",
    "pricing.growth.description": "Medium forwarders",
    "pricing.growth.price": "499",
    "pricing.growth.features1": "150 docs/mo",
    "pricing.growth.features2": "Up to 200K CHF/month + Gain-Sharing",
    "pricing.growth.features3": "300 docs/mo",
    "pricing.growth.features4": "0.10–0.15%/day + 20CHF/service fee",
    "pricing.growth.features5": "Iris Support + priority email",
    "pricing.growth.features6": "2 CHF/doc (service initiator)",
    "pricing.growth.features7": "20K CHF per site/legal entity",
    "pricing.unlimited.title": "Unlimited",
    "pricing.unlimited.description": "Large forwarders & shippers",
    "pricing.unlimited.price": "On-demand",
    "pricing.unlimited.features1": "Unlimited docs/mo",
    "pricing.unlimited.features2": "Unlimited CHF/month + Gain-Sharing",
    "pricing.unlimited.features3": "Unlimited docs/mo",
    "pricing.unlimited.features4": "0.10–0.15%/day + 20CHF/service fee",
    "pricing.unlimited.features5":
      "Iris Support + dedicated account management",
    "pricing.unlimited.features6": "1 CHF/doc (service initiator)",
    "pricing.unlimited.features7": "On demand",
    "pricing.get_started": "Get started",
    "princing.starter_7_days_free": "7 days free trial",
    "princing.starter.free_trial": "Start Free trial",
    "prining.starter_contact_sales": "Contact sales",
    "princing.more_details":
      "Credit card required for automated billing after trial",
    "princing.free.title": "Free Trial",
    "princing.free.description": "Small carriers",
    "princing.free.feature1.title": "e-CMR/e-PoD",
    "princing.free.feature1.detail": "10 docs/month",
    "princing.free.feature2.title": "Duration",
    "princing.free.feature2.detail": "15 days",
    "princing.free.feature3.title": "Support",
    "princing.free.feature3.detail": "Iris Support",
    "princing.free.feature4.title": "Invoice Verification",
    "princing.free.feature4.detail": "Basic AI-powered",
    "pricing.most_popular": "Most popular",
  },
  fr: {
    "pricing.title": "Tarification transparente pour le transport routier",
    "pricing.description":
      "Choisissez le plan qui convient à la taille de votre entreprise. Tous les plans incluent nos quatre services principaux : e-CMR/e-PoD, e-Invoicing, audit de fret et factoring.",
    "pricing.features.title": "Fonctionnalités",
    "pricing.feature1": "e-CMR & e-PoD",
    "pricing.feature2": "Vérification des factures",
    "pricing.feature3": "e-Invoicing",
    "pricing.feature4": "Factoring",
    "pricing.feature5": "Support",
    "pricing.feature6": "Frais transactionnels",
    "pricing.feature7": "Intégration & Calibration",
    "pricing.currency": "CHF",
    "priciing.time": "/mois/utilisateur",
    "pricing.starter.title": "Démarrage",
    "pricing.starter.description": "Transporteurs & petits transitaires",
    "pricing.starter.price": "199",
    "pricing.starter.features1": "10 docs/mo",
    "pricing.starter.features2": "Jusqu'à 50K CHF/mois",
    "pricing.starter.features3": "75 docs/mo",
    "pricing.starter.features4": ".10–0.15%/jour + 20CHF/frais de service",
    "pricing.starter.features5": "Support Iris",
    "pricing.starter.features6": "3CHF/doc (initiateur du service)",
    "pricing.starter.features7": "Aucun",
    "pricing.growth.title": "Croissance",
    "pricing.growth.description": "Transitaires moyens",
    "pricing.growth.price": "499",
    "pricing.growth.features1": "150 docs/mo",
    "pricing.growth.features2": "Jusqu'à 200K CHF/mois + Gain-Sharing",
    "pricing.growth.features3": "300 docs/mo",
    "pricing.growth.features4": "0.10–0.15%/jour + 20CHF/frais de service",
    "pricing.growth.features5": "Support Iris + email prioritaire",
    "pricing.growth.features6": "2 CHF/doc (initiateur du service)",
    "pricing.growth.features7": "20K CHF par site/entité légale",
    "pricing.unlimited.title": "Illimité",
    "pricing.unlimited.description":
      "Transitaires et expéditeurs de grande taille",
    "pricing.unlimited.price": "Sur demande",
    "pricing.unlimited.features1": "Docs illimités/mo",
    "pricing.unlimited.features2": "CHF illimités/mois + Gain-Sharing",
    "pricing.unlimited.features3": "Docs illimités/mo",
    "pricing.unlimited.features4": "0.10–0.15%/jour + 20CHF/frais de service",
    "pricing.unlimited.features5": "Support Iris + gestion de compte dédiée",
    "pricing.unlimited.features6": "1 CHF/doc (initiateur du service)",
    "pricing.unlimited.features7": "Sur demande",
    "pricing.get_started": "Commencer",
    "princing.starter_7_days_free": "Essai gratuit de 7 jours",
    "princing.starter.free_trial": "Démarrer l'essai gratuit",
    "prining.starter_contact_sales": "Contacter les ventes",
    "princing.more_details":
      "Carte de crédit requise pour la facturation automatique après l'essai",
    "princing.free.title": "Essai gratuit",
    "princing.free.description": "Petits transporteurs",
    "princing.free.feature1.title": "e-CMR/e-PoD",
    "princing.free.feature1.detail": "10 docs/mois",
    "princing.free.feature2.title": "Durée",
    "princing.free.feature2.detail": "15 jours",
    "princing.free.feature3.title": "Support",
    "princing.free.feature3.detail": "Support Iris",
    "princing.free.feature4.title": "Vérification des factures",
    "princing.free.feature4.detail": "Basique alimenté par IA",
    "pricing.most_popular": "Le plus populaire",
  },
  es: {
    "pricing.title": "Tarifas transparentes para el transporte por carretera",
    "pricing.description":
      "Elige el plan que se adapte al tamaño de tu negocio. Todos los planes incluyen nuestros cuatro servicios principales: e-CMR/e-PoD, facturación electrónica, auditoría de carga y factoring.",
    "pricing.features.title": "Características",
    "pricing.feature1": "e-CMR & e-PoD",
    "pricing.feature2": "Verificación de facturas",
    "pricing.feature3": "Facturación electrónica",
    "pricing.feature4": "Factoring",
    "pricing.feature5": "Soporte",
    "pricing.feature6": "Tarifa transaccional",
    "pricing.feature7": "Integración y calibración",
    "pricing.currency": "CHF",
    "priciing.time": "/mes/usuario",
    "pricing.starter.title": "Inicio",
    "pricing.starter.description": "Transportistas y pequeños transitarios",
    "pricing.starter.price": "199",
    "pricing.starter.features1": "10 docs/mes",
    "pricing.starter.features2": "Hasta 50K CHF/mes",
    "pricing.starter.features3": "75 docs/mes",
    "pricing.starter.features4": ".10–0.15%/día + 20CHF/tarifa de servicio",
    "pricing.starter.features5": "Soporte Iris",
    "pricing.starter.features6": "3CHF/doc (iniciador del servicio)",
    "pricing.starter.features7": "Ninguno",
    "pricing.growth.title": "Crecimiento",
    "pricing.growth.description": "Transitarios medianos",
    "pricing.growth.price": "499",
    "pricing.growth.features1": "150 docs/mes",
    "pricing.growth.features2": "Hasta 200K CHF/mes + Ganancias compartidas",
    "pricing.growth.features3": "300 docs/mes",
    "pricing.growth.features4": "0.10–0.15%/día + 20CHF/tarifa de servicio",
    "pricing.growth.features5": "Soporte Iris + correo electrónico prioritario",
    "pricing.growth.features6": "2 CHF/doc (iniciador del servicio)",
    "pricing.growth.features7": "20K CHF por sitio/entidad legal",
    "pricing.unlimited.title": "Ilimitado",
    "pricing.unlimited.description": "Transitarios y cargadores grandes",
    "pricing.unlimited.price": "A demanda",
    "pricing.unlimited.features1": "Docs ilimitados/mes",
    "pricing.unlimited.features2": "CHF ilimitados/mes + Ganancias compartidas",
    "pricing.unlimited.features3": "Docs ilimitados/mes",
    "pricing.unlimited.features4": "0.10–0.15%/día + 20CHF/tarifa de servicio",
    "pricing.unlimited.features5": "Soporte Iris + gestión de cuenta dedicada",
    "pricing.unlimited.features6": "1 CHF/doc (iniciador del servicio)",
    "pricing.unlimited.features7": "A demanda",
    "pricing.get_started": "Empezar",
    "princing.starter_7_days_free": "Prueba gratuita de 7 días",
    "princing.starter.free_trial": "Comenzar prueba gratuita",
    "prining.starter_contact_sales": "Contactar ventas",
    "princing.more_details":
      "Se requiere tarjeta de crédito para facturación automática después de la prueba",
    "princing.free.title": "Prueba gratuita",
    "princing.free.description": "Pequeños transportistas",
    "princing.free.feature1.title": "e-CMR/e-PoD",
    "princing.free.feature1.detail": "10 docs/mes",
    "princing.free.feature2.title": "Duración",
    "princing.free.feature2.detail": "15 días",
    "princing.free.feature3.title": "Soporte",
    "princing.free.feature3.detail": "Soporte Iris",
    "princing.free.feature4.title": "Verificación de facturas",
    "princing.free.feature4.detail": "Básico impulsado por IA",
    "pricing.most_popular": "Más popular",
  },
  de: {
    "pricing.title": "Transparente Preise für Straßentransporte",
    "pricing.description":
      "Wählen Sie den Plan, der zu Ihrer Unternehmensgröße passt. Alle Pläne beinhalten unsere vier Kernservices: e-CMR/e-PoD, e-Rechnungsstellung, Frachtprüfung und Factoring.",
    "pricing.features.title": "Funktionen",
    "pricing.feature1": "e-CMR & e-PoD",
    "pricing.feature2": "Rechnungsprüfung",
    "pricing.feature3": "e-Rechnungsstellung",
    "pricing.feature4": "Factoring",
    "pricing.feature5": "Support",
    "pricing.feature6": "Transaktionsgebühr",
    "pricing.feature7": "Integration & Kalibrierung",
    "pricing.currency": "CHF",
    "priciing.time": "/Monat/Nutzer",
    "pricing.starter.title": "Starter",
    "pricing.starter.description": "Spediteure & kleine Frachtführer",
    "pricing.starter.price": "199",
    "pricing.starter.features1": "10 Dokumente/Monat",
    "pricing.starter.features2": "Bis zu 50K CHF/Monat",
    "pricing.starter.features3": "75 Dokumente/Monat",
    "pricing.starter.features4": ".10–0.15%/Tag + 20CHF Servicegebühr",
    "pricing.starter.features5": "Iris Support",
    "pricing.starter.features6": "3CHF/Dokument (Serviceinitiator)",
    "pricing.starter.features7": "Keine",
    "pricing.growth.title": "Wachstum",
    "pricing.growth.description": "Mittlere Spediteure",
    "pricing.growth.price": "499",
    "pricing.growth.features1": "150 Dokumente/Monat",
    "pricing.growth.features2": "Bis zu 200K CHF/Monat + Gewinnbeteiligung",
    "pricing.growth.features3": "300 Dokumente/Monat",
    "pricing.growth.features4": "0.10–0.15%/Tag + 20CHF Servicegebühr",
    "pricing.growth.features5": "Iris Support + priorisierte E-Mail",
    "pricing.growth.features6": "2 CHF/Dokument (Serviceinitiator)",
    "pricing.growth.features7": "20K CHF pro Standort/rechtliche Einheit",
    "pricing.unlimited.title": "Unbegrenzt",
    "pricing.unlimited.description": "Große Spediteure & Versender",
    "pricing.unlimited.price": "Auf Anfrage",
    "pricing.unlimited.features1": "Unbegrenzte Dokumente/Monat",
    "pricing.unlimited.features2": "Unbegrenzte CHF/Monat + Gewinnbeteiligung",
    "pricing.unlimited.features3": "Unbegrenzte Dokumente/Monat",
    "pricing.unlimited.features4": "0.10–0.15%/Tag + 20CHF Servicegebühr",
    "pricing.unlimited.features5": "Iris Support + dedizierte Kontoverwaltung",
    "pricing.unlimited.features6": "1 CHF/Dokument (Serviceinitiator)",
    "pricing.unlimited.features7": "Auf Anfrage",
    "pricing.get_started": "Loslegen",
    "princing.starter_7_days_free": "7 Tage kostenlos testen",
    "princing.starter.free_trial": "Kostenlose Testversion starten",
    "prining.starter_contact_sales": "Kontaktieren Sie den Vertrieb",
    "princing.more_details":
      "Kreditkarte erforderlich für automatisierte Abrechnung nach der Testphase",
    "princing.free.title": "Kostenlose Testversion",
    "princing.free.description": "Kleine Spediteure",
    "princing.free.feature1.title": "e-CMR/e-PoD",
    "princing.free.feature1.detail": "10 Dokumente/Monat",
    "princing.free.feature2.title": "Dauer",
    "princing.free.feature2.detail": "15 Tage",
    "princing.free.feature3.title": "Support",
    "princing.free.feature3.detail": "Iris Support",
    "princing.free.feature4.title": "Rechnungsprüfung",
    "princing.free.feature4.detail": "Grundlegend KI-gestützt",
    "pricing.most_popular": "Am beliebtesten",
  },
} as const;
